### ISSUE TITLE
请问我在arm64的软路由docker里运行不起来是不兼容吗？

### ISSUE THREAD

**Issue by Lostwhr** [eMUQI/baidunetdisk-arm64-vnc#1]
stdout:     ╭――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╮
stdout:     │                                                                      │
stdout:     │ Application:           Baidunetdisk                                  │
stdout:     │ Application Version:   n/a                                           │
stdout:     │ Docker Image Version:  n/a                                           │
stdout:     │ Docker Image Platform: linux/arm64                                   │
stdout:     │                                                                      │
stdout:     ╰――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╯
stdout: [cont-init   ] 89-info.sh: terminated successfully.
stdout: [cont-init   ] all container initialization scripts executed.
stdout: [init        ] giving control to process supervisor.
stdout: [supervisor  ] loading services...
stdout: [supervisor  ] loading service 'default'...
stdout: [supervisor  ] loading service 'logmonitor'...
stdout: [supervisor  ] service 'logmonitor' is disabled.
stdout: [supervisor  ] loading service 'app'...
stdout: [supervisor  ] loading service 'gui'...
stdout: [supervisor  ] loading service 'xvnc'...
stdout: [supervisor  ] loading service 'certsmonitor'...
stdout: [supervisor  ] service 'certsmonitor' is disabled.
stdout: [supervisor  ] loading service 'jwm'...
stdout: [supervisor  ] loading service 'nginx'...
stdout: [supervisor  ] all services loaded.
stdout: [supervisor  ] starting services...
stdout: [supervisor  ] starting service 'xvnc'...
stdout: [xvnc        ] Xvnc TigerVNC 1.12.0 - built Dec 11 2022 21:00:18
stdout: [xvnc        ] Copyright (C) 1999-2021 TigerVNC Team and many others (see README.rst)
stdout: [xvnc        ] See https://www.tigervnc.org for information on TigerVNC.
stdout: [xvnc        ] Underlying X server release 12013000, The X.Org Foundation
stdout: [xvnc        ] Tue Jun  6 16:26:33 2023
stdout: [xvnc        ]  vncext:      VNC extension running!
stdout: [xvnc        ]  vncext:      Listening for VNC connections on /tmp/vnc.sock (mode 0660)
stdout: [xvnc        ]  vncext:      Listening for VNC connections on all interface(s), port 5900
stdout: [xvnc        ]  vncext:      created VNC server for screen 0
stdout: [supervisor  ] starting service 'jwm'...
stdout: [supervisor  ] starting service 'nginx'...
stdout: [nginx       ] Listening for HTTP connections on port 5800.
stdout: [supervisor  ] starting service 'app'...
stdout: [supervisor  ] all services started.
stdout: [app         ] cmdProcess stderr: sed: can't read /config/.config/mimeapps.list: No such file or directory
stdout: [app         ] ndevice name: pppoe-wan
stdout: [app         ] browser engine version: 1.0.4.13
stdout: [app         ] (baidunetdisk:575): libappindicator-[1;33mWARNING[0m **: [34m16:26:44.904[0m: Unable to get the session bus: Unknown or unsupported transport ?disabled? for address ?disabled:?
stdout: [app         ] (baidunetdisk:575): LIBDBUSMENU-GLIB-[1;33mWARNING[0m **: [34m16:26:44.913[0m: Unable to get session bus: Unknown or unsupported transport ?disabled? for address ?disabled:?
stdout: [supervisor  ] service 'app' exited (with status 0).
stdout: [supervisor  ] service 'app' exited, shutting down...
stdout: [supervisor  ] stopping service 'nginx'...
stdout: [supervisor  ] service 'nginx' exited (with status 0).
stdout: [supervisor  ] stopping service 'jwm'...
stdout: [supervisor  ] service 'jwm' exited (with status 0).
stdout: [supervisor  ] stopping service 'xvnc'...
stdout: [xvnc        ] Tue Jun  6 16:26:45 2023
stdout: [xvnc        ]  ComparingUpdateTracker: 0 pixels in / 0 pixels out
stdout: [xvnc        ]  ComparingUpdateTracker: (1:nan ratio)
stdout: [supervisor  ] service 'xvnc' exited (with status 0).
stdout: [finish      ] executing container finish scripts...
stdout: [finish      ] all container finish scripts executed.
stdout: [init        ] container is starting...
stdout: [cont-env    ] loading container environment variables...
stdout: [cont-env    ] APP_NAME: loading...
stdout: [cont-env    ] DISPLAY: executing...
stdout: [cont-env    ] DISPLAY: terminated successfully.
stdout: [cont-env    ] DISPLAY: loading...
stdout: [cont-env    ] DOCKER_IMAGE_PLATFORM: loading...
stdout: [cont-env    ] GTK_THEME: executing...
stdout: [cont-env    ] GTK_THEME: terminated successfully.
stdout: [cont-env    ] GTK_THEME: loading...
stdout: [cont-env    ] HOME: loading...
stdout: [cont-env    ] QT_STYLE_OVERRIDE: executing...
stdout: [cont-env    ] QT_STYLE_OVERRIDE: terminated successfully.
stdout: [cont-env    ] QT_STYLE_OVERRIDE: loading...
stdout: [cont-env    ] TAKE_CONFIG_OWNERSHIP: loading...
stdout: [cont-env    ] XDG_CACHE_HOME: loading...
stdout: [cont-env    ] XDG_CONFIG_HOME: loading...
stdout: [cont-env    ] XDG_DATA_HOME: loading...
stdout: [cont-env    ] XDG_RUNTIME_DIR: loading...
stdout: [cont-env    ] container environment variables initialized.
stdout: [cont-secrets] loading container secrets...
stdout: [cont-secrets] container secrets loaded.
stdout: [cont-init   ] executing container initialization scripts...
stdout: [cont-init   ] 10-certs.sh: executing...
stdout: [cont-init   ] 10-certs.sh: terminated successfully.
stdout: [cont-init   ] 10-check-app-niceness.sh: executing...
stdout: [cont-init   ] 10-check-app-niceness.sh: terminated successfully.
stdout: [cont-init   ] 10-cjk-font.sh: executing...
stdout: [cont-init   ] 10-cjk-font.sh: terminated successfully.
stdout: [cont-init   ] 10-clean-logmonitor-states.sh: executing...
stdout: [cont-init   ] 10-clean-logmonitor-states.sh: terminated successfully.
stdout: [cont-init   ] 10-clean-tmp-dir.sh: executing...
stdout: [cont-init   ] 10-clean-tmp-dir.sh: terminated successfully.
stdout: [cont-init   ] 10-fontconfig-cache-dir.sh: executing...
stdout: [cont-init   ] 10-fontconfig-cache-dir.sh: terminated successfully.
stdout: [cont-init   ] 10-init-users.sh: executing...
stdout: [cont-init   ] 10-init-users.sh: terminated successfully.
stdout: [cont-init   ] 10-jwm.sh: executing...
stdout: [cont-init   ] 10-jwm.sh: terminated successfully.
stdout: [cont-init   ] 10-nginx.sh: executing...
stdout: [cont-init   ] 10-nginx.sh: terminated successfully.
stdout: [cont-init   ] 10-novnc-language-set.sh: executing...
stdout: [cont-init   ] 10-novnc-language-set.sh: terminated successfully.
stdout: [cont-init   ] 10-set-tmp-dir-perms.sh: executing...
stdout: [cont-init   ] 10-set-tmp-dir-perms.sh: terminated successfully.
stdout: [cont-init   ] 10-vnc-password.sh: executing...
stdout: [cont-init   ] 10-vnc-password.sh: terminated successfully.
stdout: [cont-init   ] 10-web-data.sh: executing...
stdout: [cont-init   ] 10-web-data.sh: terminated successfully.
stdout: [cont-init   ] 10-x11-unix.sh: executing...
stdout: [cont-init   ] 10-x11-unix.sh: terminated successfully.
stdout: [cont-init   ] 10-xdg-runtime-dir.sh: executing...
stdout: [cont-init   ] 10-xdg-runtime-dir.sh: terminated successfully.
stdout: [cont-init   ] 15-install-pkgs.sh: executing...
stdout: [cont-init   ] 15-install-pkgs.sh: terminated successfully.
stdout: [cont-init   ] 85-take-config-ownership.sh: executing...
stdout: [cont-init   ] 85-take-config-ownership.sh: terminated successfully.
stdout: [cont-init   ] 89-info.sh: executing...

**Comment by eMUQI** [comment]
尝试重启容器看看能否解决，这个镜像是兼容arm64设备的。
