### ISSUE TITLE
新版本

### ISSUE THREAD

**Issue by maolei1024** [eMUQI/baidunetdisk-arm64-vnc#2]
![image](https://github.com/eMUQI/baidunetdisk-arm64-vnc/assets/64685627/f89f2963-0a57-4851-9b81-4cf6c0113315)
# 新版本升级,望同步

**Comment by eMUQI** [comment]
感谢反馈，已同步4.17.7版本。

![image](https://github.com/eMUQI/baidunetdisk-arm64-vnc/assets/32332228/9984415f-90de-4294-878a-659a068daa77)
